resources:
  - namespaces.yaml
  - apps/infisical-operator.yaml
  - apps/infisical-bootstrap.yaml
  - apps/monitoring.yaml
  - apps/logging.yaml
  - apps/promtail.yaml
  - apps/netbird-operator.yaml
  - apps/netbird-operator-config.yaml
