# clusters/base/kustomization.yaml
resources:
  - namespaces.yaml
  - ../../platform/monitoring/application.yaml
  - ../../platform/logging/application.yaml
  - ../../platform/promtail/application.yaml
